//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnthraX.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.6.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ThemeType {
            get {
                return ((int)(this["ThemeType"]));
            }
            set {
                this["ThemeType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public string ThemeColorName {
            get {
                return ((string)(this["ThemeColorName"]));
            }
            set {
                this["ThemeColorName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color ThemeCustomColor {
            get {
                return ((global::System.Drawing.Color)(this["ThemeCustomColor"]));
            }
            set {
                this["ThemeCustomColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int ThemeWallpaperType {
            get {
                return ((int)(this["ThemeWallpaperType"]));
            }
            set {
                this["ThemeWallpaperType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public string ThemeWallpaperColor {
            get {
                return ((string)(this["ThemeWallpaperColor"]));
            }
            set {
                this["ThemeWallpaperColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color ThemeWallpaperCustomColor {
            get {
                return ((global::System.Drawing.Color)(this["ThemeWallpaperCustomColor"]));
            }
            set {
                this["ThemeWallpaperCustomColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public int ThemeWallpaperImage {
            get {
                return ((int)(this["ThemeWallpaperImage"]));
            }
            set {
                this["ThemeWallpaperImage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ThemeWallpaperCustomImage {
            get {
                return ((string)(this["ThemeWallpaperCustomImage"]));
            }
            set {
                this["ThemeWallpaperCustomImage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public int ThemeWallpaperDrawType {
            get {
                return ((int)(this["ThemeWallpaperDrawType"]));
            }
            set {
                this["ThemeWallpaperDrawType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ThemeDarkMode {
            get {
                return ((bool)(this["ThemeDarkMode"]));
            }
            set {
                this["ThemeDarkMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ThemeEnabledTransparency {
            get {
                return ((bool)(this["ThemeEnabledTransparency"]));
            }
            set {
                this["ThemeEnabledTransparency"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("128")]
        public int ThemeTransparency {
            get {
                return ((int)(this["ThemeTransparency"]));
            }
            set {
                this["ThemeTransparency"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9")]
        public int SpectrumType {
            get {
                return ((int)(this["SpectrumType"]));
            }
            set {
                this["SpectrumType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SpectrumFillType {
            get {
                return ((int)(this["SpectrumFillType"]));
            }
            set {
                this["SpectrumFillType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public string SpectrumColor {
            get {
                return ((string)(this["SpectrumColor"]));
            }
            set {
                this["SpectrumColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color SpectrumCustomColor {
            get {
                return ((global::System.Drawing.Color)(this["SpectrumCustomColor"]));
            }
            set {
                this["SpectrumCustomColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SpectrumEnableTransparency {
            get {
                return ((bool)(this["SpectrumEnableTransparency"]));
            }
            set {
                this["SpectrumEnableTransparency"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("224")]
        public int SpectrumTransparency {
            get {
                return ((int)(this["SpectrumTransparency"]));
            }
            set {
                this["SpectrumTransparency"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SpectrumFillStyle {
            get {
                return ((int)(this["SpectrumFillStyle"]));
            }
            set {
                this["SpectrumFillStyle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("768")]
        public int SpectrumSensitivity {
            get {
                return ((int)(this["SpectrumSensitivity"]));
            }
            set {
                this["SpectrumSensitivity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("128")]
        public int SpectrumSize {
            get {
                return ((int)(this["SpectrumSize"]));
            }
            set {
                this["SpectrumSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int SpectrumLogo {
            get {
                return ((int)(this["SpectrumLogo"]));
            }
            set {
                this["SpectrumLogo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("16")]
        public int PlayerInformationTimeout {
            get {
                return ((int)(this["PlayerInformationTimeout"]));
            }
            set {
                this["PlayerInformationTimeout"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool PlayerNotification {
            get {
                return ((bool)(this["PlayerNotification"]));
            }
            set {
                this["PlayerNotification"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool PlayerTaskbarPosition {
            get {
                return ((bool)(this["PlayerTaskbarPosition"]));
            }
            set {
                this["PlayerTaskbarPosition"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PlayerAutoStart {
            get {
                return ((bool)(this["PlayerAutoStart"]));
            }
            set {
                this["PlayerAutoStart"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PlayerAutoBack {
            get {
                return ((bool)(this["PlayerAutoBack"]));
            }
            set {
                this["PlayerAutoBack"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int SpectrumRainbowSpeed {
            get {
                return ((int)(this["SpectrumRainbowSpeed"]));
            }
            set {
                this["SpectrumRainbowSpeed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("16")]
        public int SpectrumRainbowColor {
            get {
                return ((int)(this["SpectrumRainbowColor"]));
            }
            set {
                this["SpectrumRainbowColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int ExplorerView {
            get {
                return ((int)(this["ExplorerView"]));
            }
            set {
                this["ExplorerView"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int EqualizerPresetIndex {
            get {
                return ((int)(this["EqualizerPresetIndex"]));
            }
            set {
                this["EqualizerPresetIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int EqualizerEffectIndex {
            get {
                return ((int)(this["EqualizerEffectIndex"]));
            }
            set {
                this["EqualizerEffectIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AnimationSpec {
            get {
                return ((bool)(this["AnimationSpec"]));
            }
            set {
                this["AnimationSpec"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("189, 182")]
        public global::System.Drawing.Point FormPosition {
            get {
                return ((global::System.Drawing.Point)(this["FormPosition"]));
            }
            set {
                this["FormPosition"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("900, 600")]
        public global::System.Drawing.Size FormSize {
            get {
                return ((global::System.Drawing.Size)(this["FormSize"]));
            }
            set {
                this["FormSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("300")]
        public int NowPlayingWidth {
            get {
                return ((int)(this["NowPlayingWidth"]));
            }
            set {
                this["NowPlayingWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool PlayerAutoSave {
            get {
                return ((bool)(this["PlayerAutoSave"]));
            }
            set {
                this["PlayerAutoSave"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public int SoundVolume {
            get {
                return ((int)(this["SoundVolume"]));
            }
            set {
                this["SoundVolume"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool KaraokeEnabled {
            get {
                return ((bool)(this["KaraokeEnabled"]));
            }
            set {
                this["KaraokeEnabled"] = value;
            }
        }
    }
}
